#pragma once

// Model-specific chat protocols live behind this descriptor. The HTTP server
// knows only that a codec can turn an OpenAI-shaped request into a prompt and
// can turn generated bytes back into an OpenAI-shaped assistant message.

#include "soma/types.hpp"

#include <nlohmann/json_fwd.hpp>

#include <string>
#include <string_view>

namespace soma {

struct PromptCodecState {
    /// Opaque to the server. A codec may use it to distinguish two official
    /// completion grammars selected while encoding the request.
    bool mode = false;
};

struct PromptCodec {
    const char* name = nullptr;

    // ordered_json is intentional: DSML embeds tool schemas and response
    // formats verbatim in the token stream. Losing the caller's object-key
    // order while parsing HTTP JSON changes that stream and no longer matches
    // the model's official encoder.
    Status (*encode)(const nlohmann::ordered_json& request,
                     std::string& prompt,
                     PromptCodecState& state) noexcept = nullptr;

    /// Parse the stable prefix of `completion`. With final=false an unfinished
    /// delimiter is retained rather than exposed as content. With final=true,
    /// malformed protocol syntax is an explicit error.
    Status (*parse)(std::string_view completion,
                    const PromptCodecState& state,
                    bool final,
                    bool ended_by_stop,
                    nlohmann::json& message) noexcept = nullptr;
};

} // namespace soma
