#pragma once

// Model-specific chat protocols live behind this descriptor. The HTTP server
// knows only that a codec can turn an OpenAI-shaped request into a prompt and
// can turn generated bytes back into an OpenAI-shaped assistant message.

#include "soma/types.hpp"

#include <string>
#include <string_view>
#include <vector>

namespace soma {

struct PromptCodecState {
    /// Opaque to the server. A codec may use it to distinguish two official
    /// completion grammars selected while encoding the request.
    bool mode = false;
};

struct PromptToolCall {
    std::string id;
    std::string name;
    std::string arguments;
};

struct PromptMessage {
    std::string content;
    std::string reasoning_content;
    std::vector<PromptToolCall> tool_calls;
};

struct PromptCodec {
    const char* name = nullptr;

    // The codec owns JSON parsing so this public descriptor remains a
    // standard-library-only boundary. DSML parses the bytes as ordered JSON:
    // tool schemas and response formats are embedded verbatim in the prompt,
    // so losing the caller's object-key order would change the token stream.
    Status (*encode)(std::string_view request_json,
                     std::string& prompt,
                     PromptCodecState& state) noexcept = nullptr;

    /// Parse the stable prefix of `completion`. With final=false an unfinished
    /// delimiter is retained rather than exposed as content. With final=true,
    /// malformed protocol syntax is an explicit error.
    Status (*parse)(std::string_view completion,
                    const PromptCodecState& state,
                    bool final,
                    bool ended_by_stop,
                    PromptMessage& message) noexcept = nullptr;
};

} // namespace soma
