// Soma — the KDA kernel against fla's own.
//
// `soma_kda_kernel` grades the recurrence on identities derived from what a
// delta rule is supposed to do. That found six distinct misreadings, and it is
// still a second opinion from the same reader: a consistently wrong reading of
// the reference satisfies every identity it inspired.
//
// This is the external check. The fixture is the SAME inputs run through
// `fla.ops.kda.fused_recurrent_kda` — the implementation `modeling_kimi_linear.py`
// actually calls — at the exact flags Kimi-K3 passes it:
// `use_qk_l2norm_in_kernel`, `use_gate_in_kernel`, `use_beta_sigmoid_in_kernel`,
// and `safe_gate` with `lower_bound=-5.0`. Generated by
// tools/admission/make_kda_oracle.py, which needs CUDA because fla's kernels are
// Triton.
//
// WHAT IT CANNOT SAY. Production prefill calls `chunk_kda`, not the recurrent
// kernel, and fla's two kernels disagree with each other by 5.8e-04 on random
// input. So this pins Soma to fla's RECURRENCE tightly, and to fla's chunked
// prefill only to about 1e-03 — a limit of the reference, not of Soma.

#include "soma/arch/kda.hpp"
#include "soma/arch_ir.hpp"

#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace {

bool check(bool value, const char* expression, int line) {
    if (value) return true;
    std::cerr << "FAIL line " << line << ": " << expression << '\n';
    return false;
}

#define CHECK(expr)                                                                                \
    do {                                                                                           \
        if (!check((expr), #expr, __LINE__)) return 1;                                             \
    } while (false)

struct Fixture {
    std::uint32_t heads = 0, head_dim = 0, tokens = 0, has_bound = 0;
    float gate_lower_bound = 0.0f;
    std::vector<float> a_log, dt_bias, q, k, v, g_raw, beta_raw, o, state;
};

bool read_fixture(const std::string& path, Fixture& f) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        std::cerr << "cannot open " << path << '\n';
        return false;
    }
    char magic[8]{};
    in.read(magic, 8);
    if (std::memcmp(magic, "SOMAKDA1", 8) != 0) {
        std::cerr << "bad magic in " << path << '\n';
        return false;
    }
    in.read(reinterpret_cast<char*>(&f.heads), 4);
    in.read(reinterpret_cast<char*>(&f.head_dim), 4);
    in.read(reinterpret_cast<char*>(&f.tokens), 4);
    in.read(reinterpret_cast<char*>(&f.has_bound), 4);
    in.read(reinterpret_cast<char*>(&f.gate_lower_bound), 4);

    const auto H = f.heads, D = f.head_dim, T = f.tokens;
    const auto P = static_cast<std::size_t>(H) * D;
    const auto load = [&](std::vector<float>& dst, std::size_t n) {
        dst.resize(n);
        in.read(reinterpret_cast<char*>(dst.data()), static_cast<std::streamsize>(n * 4));
    };
    load(f.a_log, H);
    load(f.dt_bias, P);
    load(f.q, static_cast<std::size_t>(T) * P);
    load(f.k, static_cast<std::size_t>(T) * P);
    load(f.v, static_cast<std::size_t>(T) * P);
    load(f.g_raw, static_cast<std::size_t>(T) * P);
    load(f.beta_raw, static_cast<std::size_t>(T) * H);
    load(f.o, static_cast<std::size_t>(T) * P);
    load(f.state, P * D);
    return static_cast<bool>(in);
}

} // namespace

int main(int argc, char** argv) {
    const std::string dir = argc > 1 ? argv[1] : "tests/fixtures/kernels/kda";
    Fixture f;
    CHECK(read_fixture(dir + "/kda_oracle.bin", f));
    CHECK(f.heads > 0 && f.head_dim > 0 && f.tokens > 0);

    soma::ArchIr arch;
    arch.attention.family = soma::AttentionFamily::MlaKda;
    arch.topology.n_layers = 1;
    arch.topology.d_model = f.heads * f.head_dim;
    arch.topology.vocab_size = 8;
    arch.topology.layer_kinds.assign(1, soma::LayerKind::Moe);
    auto& cfg = arch.attention.kda;
    cfg.n_heads = f.heads;
    cfg.head_dim = f.head_dim;
    cfg.conv_kernel = 4; // unused here: the fixture feeds post-convolution q/k/v
    cfg.layer_kinds.assign(1, soma::AttnLayerKind::Linear);
    cfg.has_gate_bound = f.has_bound != 0;
    cfg.gate_lower_bound = f.gate_lower_bound;

    const auto P = static_cast<std::size_t>(f.heads) * f.head_dim;
    std::vector<float> state(P * f.head_dim, 0.0f);
    std::vector<float> scratch(f.head_dim), gbuf(P), out(P);

    double worst_o = 0.0;
    std::uint32_t worst_at = 0;
    for (std::uint32_t t = 0; t < f.tokens; ++t) {
        const auto off = static_cast<std::size_t>(t) * P;
        soma::arch::kda::gate(arch, f.a_log.data(), f.dt_bias.data(), f.g_raw.data() + off,
                              gbuf.data());
        soma::arch::kda::step(arch, f.q.data() + off, f.k.data() + off, f.v.data() + off,
                              gbuf.data(), f.beta_raw.data() + static_cast<std::size_t>(t) * f.heads,
                              state.data(), scratch.data(), out.data());
        for (std::size_t i = 0; i < P; ++i) {
            const double d = std::fabs(static_cast<double>(out[i]) - f.o[off + i]);
            if (d > worst_o) {
                worst_o = d;
                worst_at = t;
            }
        }
    }

    // The FINAL STATE, not only the outputs. A kernel can track the reference's
    // output for a while on a state that is drifting — the readout is a
    // projection of it, and projections hide error. This is the part a
    // long conversation depends on.
    double worst_s = 0.0;
    for (std::size_t i = 0; i < state.size() && i < f.state.size(); ++i)
        worst_s = std::max(worst_s, std::fabs(static_cast<double>(state[i]) - f.state[i]));

    // Absolute, because the reference's own magnitudes here are ~1e-01 and a
    // relative bound on values that pass through zero is not a bound at all.
    //
    // MEASURED, then bounded with stated margin — not guessed and rounded up.
    //
    // Observed on an RTX 5090 against fla 0.5.2 / torch 2.11.0+cu128:
    // max|do| = 2.24e-08 at step 44, max|dS| = 2.98e-08. That is fp32 round-off
    // over 48 sequential steps with one side accumulating in a Triton kernel on
    // the GPU and the other in scalar C++ on the CPU — i.e. the two agree to the
    // precision the format allows.
    //
    // 1e-07 leaves ~3x headroom for a different GPU or driver while staying two
    // orders inside anything a real defect would produce. A first draft of this
    // test used 2e-06 on a guess; the measurement says that was 100x too loose,
    // and a bound that loose would have accepted a genuinely wrong kernel.
    constexpr double kTol = 1e-7;
    CHECK(worst_o < kTol);
    CHECK(worst_s < kTol);

    // The fixture has to be capable of failing. An oracle of near-zeros would
    // satisfy any tolerance.
    double mag = 0.0;
    for (const auto x : f.o) mag = std::max(mag, std::fabs(static_cast<double>(x)));
    CHECK(mag > 1e-3);

    std::cout << "kda_oracle: OK (" << f.tokens << " steps, H=" << f.heads
              << " D=" << f.head_dim << ", max|do|=" << worst_o << " @t" << worst_at
              << ", max|dS|=" << worst_s << ")\n";
    return 0;
}
